BEGIN;

-- Drop in reverse dependency order for clean re-runs
DROP TABLE IF EXISTS forecasts CASCADE;
DROP TABLE IF EXISTS matches CASCADE;
DROP TABLE IF EXISTS tournament_participants CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS tournaments CASCADE;
DROP TABLE IF EXISTS teams CASCADE;

DROP TYPE IF EXISTS match_status CASCADE;
DROP TYPE IF EXISTS match_kind CASCADE;
DROP TYPE IF EXISTS sport CASCADE;

-- =======
-- TYPES
-- =======
CREATE TYPE sport AS ENUM (
    'soccer',
    'basketball',
    'baseball',
    'volleyball',
    'rugby',
    'hockey'
);

CREATE TYPE match_kind AS ENUM (
    'friendly',
    'official'
);

CREATE TYPE match_status AS ENUM (
    'scheduled',
    'live',
    'finished'
);

-- =======
-- TABLES
-- =======
CREATE TABLE teams (
    team_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    short_name VARCHAR(20) NOT NULL UNIQUE,
    sport sport NOT NULL
);

CREATE TABLE tournaments (
    tournament_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(150) NOT NULL UNIQUE,
    sport sport NOT NULL,
    season VARCHAR(50) NOT NULL
);

CREATE TABLE tournament_participants (
    participant_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tournament_id INT NOT NULL REFERENCES tournaments(tournament_id) ON DELETE CASCADE,
    team_id INT NOT NULL REFERENCES teams(team_id) ON DELETE CASCADE,
    UNIQUE (tournament_id, team_id)
);

CREATE TABLE users (
    user_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    email VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE matches (
    match_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tournament_id INT NULL REFERENCES tournaments(tournament_id) ON DELETE SET NULL,
    match_kind match_kind NOT NULL DEFAULT 'official',
    sport sport NOT NULL,
    home_team_id INT NOT NULL REFERENCES teams(team_id),
    away_team_id INT NOT NULL REFERENCES teams(team_id),
    played_at TIMESTAMPTZ NOT NULL,
    status match_status NOT NULL DEFAULT 'scheduled',
    home_score INT NULL,
    away_score INT NULL,
    stats_json JSONB NOT NULL DEFAULT '{}'::jsonb,
    CHECK (home_team_id <> away_team_id),
    CHECK (home_score IS NULL OR home_score >= 0),
    CHECK (away_score IS NULL OR away_score >= 0)
);

CREATE TABLE forecasts (
    forecast_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INT NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    match_id INT NOT NULL REFERENCES matches(match_id) ON DELETE CASCADE,
    predicted_home_score INT NOT NULL CHECK (predicted_home_score >= 0),
    predicted_away_score INT NOT NULL CHECK (predicted_away_score >= 0),
    submitted_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (user_id, match_id)
);

-- =======
-- TRIGGERS
-- =======

-- 1) A team cannot play more than one match on the same day
CREATE OR REPLACE FUNCTION prevent_same_day_double_booking()
RETURNS TRIGGER AS $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM matches m
        WHERE m.match_id <> COALESCE(NEW.match_id, -1)
          AND m.played_at::date = NEW.played_at::date
          AND (
              m.home_team_id = NEW.home_team_id
              OR m.away_team_id = NEW.home_team_id
              OR m.home_team_id = NEW.away_team_id
              OR m.away_team_id = NEW.away_team_id
          )
    ) THEN
        RAISE EXCEPTION 'A team cannot play more than one match on the same day';
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_prevent_same_day_double_booking ON matches;
CREATE TRIGGER trg_prevent_same_day_double_booking
BEFORE INSERT OR UPDATE OF home_team_id, away_team_id, played_at
ON matches
FOR EACH ROW
EXECUTE FUNCTION prevent_same_day_double_booking();

-- 2) Validate sport consistency and friendly vs official rules
CREATE OR REPLACE FUNCTION validate_match_rules()
RETURNS TRIGGER AS $$
DECLARE
    home_sport sport;
    away_sport sport;
    tournament_sport sport;
BEGIN
    -- Match must have valid teams
    SELECT sport INTO home_sport
    FROM teams
    WHERE team_id = NEW.home_team_id;

    SELECT sport INTO away_sport
    FROM teams
    WHERE team_id = NEW.away_team_id;

    IF home_sport IS NULL OR away_sport IS NULL THEN
        RAISE EXCEPTION 'Both teams must exist';
    END IF;

    IF home_sport <> away_sport THEN
        RAISE EXCEPTION 'The two teams must play the same sport';
    END IF;

    IF NEW.sport <> home_sport OR NEW.sport <> away_sport THEN
        RAISE EXCEPTION 'Match sport must match both teams';
    END IF;

    IF NEW.match_kind = 'official' THEN
        IF NEW.tournament_id IS NULL THEN
            RAISE EXCEPTION 'Official matches must belong to a tournament';
        END IF;

        SELECT sport INTO tournament_sport
        FROM tournaments
        WHERE tournament_id = NEW.tournament_id;

        IF tournament_sport IS NULL THEN
            RAISE EXCEPTION 'Tournament does not exist';
        END IF;

        IF NEW.sport <> tournament_sport THEN
            RAISE EXCEPTION 'Tournament sport must match the match sport';
        END IF;
    END IF;

    IF NEW.match_kind = 'friendly' THEN
        IF NEW.tournament_id IS NOT NULL THEN
            RAISE EXCEPTION 'Friendly matches must not be linked to a tournament';
        END IF;
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_validate_match_rules ON matches;
CREATE TRIGGER trg_validate_match_rules
BEFORE INSERT OR UPDATE OF tournament_id, match_kind, sport, home_team_id, away_team_id
ON matches
FOR EACH ROW
EXECUTE FUNCTION validate_match_rules();

-- 3) Match lifecycle rules:
-- Insert: status scheduled, scores null, played_at max 2h in future
-- Update: finished matches cannot be edited
-- scheduled -> live/finished
-- live -> finished
-- finished -> no updates
CREATE OR REPLACE FUNCTION validate_match_state()
RETURNS TRIGGER AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        IF NEW.status <> 'scheduled' THEN
            RAISE EXCEPTION 'New matches must be inserted with status scheduled';
        END IF;

        IF NEW.home_score IS NOT NULL OR NEW.away_score IS NOT NULL THEN
            RAISE EXCEPTION 'New matches cannot have scores yet';
        END IF;

        IF NEW.played_at > NOW() + INTERVAL '2 hours' THEN
            RAISE EXCEPTION 'Match time cannot be more than 2 hours in the future';
        END IF;
    END IF;

    IF TG_OP = 'UPDATE' THEN
        IF OLD.status = 'finished' THEN
            RAISE EXCEPTION 'Finished matches cannot be updated';
        END IF;

        IF NEW.status = OLD.status THEN
            RAISE EXCEPTION 'Status must change when updating a match';
        END IF;

        IF OLD.status = 'scheduled' AND NEW.status NOT IN ('live', 'finished') THEN
            RAISE EXCEPTION 'Scheduled matches can only go to live or finished';
        END IF;

        IF OLD.status = 'live' AND NEW.status <> 'finished' THEN
            RAISE EXCEPTION 'Live matches can only go to finished';
        END IF;

        IF NEW.status = 'finished' THEN
            IF NEW.home_score IS NULL OR NEW.away_score IS NULL THEN
                RAISE EXCEPTION 'Finished matches must include both scores';
            END IF;
        ELSE
            IF NEW.home_score IS NOT NULL OR NEW.away_score IS NOT NULL THEN
                RAISE EXCEPTION 'Only finished matches may have scores';
            END IF;
        END IF;
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_validate_match_state ON matches;
CREATE TRIGGER trg_validate_match_state
BEFORE INSERT OR UPDATE OF status, home_score, away_score
ON matches
FOR EACH ROW
EXECUTE FUNCTION validate_match_state();

-- 4) Forecast must be submitted no earlier than 1 hour before kickoff
CREATE OR REPLACE FUNCTION validate_forecast_submission()
RETURNS TRIGGER AS $$
DECLARE
    kick_off TIMESTAMPTZ;
BEGIN
    SELECT played_at INTO kick_off
    FROM matches
    WHERE match_id = NEW.match_id;

    IF kick_off IS NULL THEN
        RAISE EXCEPTION 'Referenced match does not exist';
    END IF;

    IF NEW.submitted_at < kick_off - INTERVAL '1 hour' THEN
        RAISE EXCEPTION 'Forecast cannot be submitted more than 1 hour before the match';
    END IF;

    IF NEW.submitted_at > kick_off THEN
        RAISE EXCEPTION 'Forecast cannot be submitted after the match starts';
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_validate_forecast_submission ON forecasts;
CREATE TRIGGER trg_validate_forecast_submission
BEFORE INSERT OR UPDATE OF match_id, submitted_at
ON forecasts
FOR EACH ROW
EXECUTE FUNCTION validate_forecast_submission();

-- =======
-- SAMPLE DATA
-- =======

INSERT INTO teams (name, short_name, sport)
VALUES
    ('Real Madrid', 'RMA', 'soccer'),
    ('Barcelona', 'BAR', 'soccer'),
    ('Osasuna', 'OSA', 'soccer'),
    ('Atlético Madrid', 'ATM', 'soccer')
ON CONFLICT (name) DO NOTHING;

INSERT INTO tournaments (name, sport, season)
VALUES
    ('Spain 2026 Winter Championship', 'soccer', '2026')
ON CONFLICT (name) DO NOTHING;

INSERT INTO tournament_participants (tournament_id, team_id)
VALUES
    (1, 1),
    (1, 2),
    (1, 3),
    (1, 4)
ON CONFLICT (tournament_id, team_id) DO NOTHING;

INSERT INTO users (username, email)
VALUES
    ('ana', 'ana@example.com'),
    ('pablo', 'pablo@example.com'),
    ('carlos', 'carlos@example.com')
ON CONFLICT (username) DO NOTHING;

INSERT INTO matches (
    tournament_id,
    match_kind,
    sport,
    home_team_id,
    away_team_id,
    played_at,
    status,
    home_score,
    away_score,
    stats_json
)
VALUES
    (
        1,
        'official',
        'soccer',
        1,
        2,
        '2026-01-12 18:00:00+00',
        'finished',
        2,
        1,
        '{"possession":{"home":58,"away":42},"shots":{"home":12,"away":7}}'
    ),
    (
        1,
        'official',
        'soccer',
        3,
        4,
        '2026-01-13 20:00:00+00',
        'finished',
        1,
        1,
        '{"possession":{"home":49,"away":51},"shots":{"home":9,"away":10}}'
    ),
    (
        1,
        'official',
        'soccer',
        2,
        4,
        '2026-01-20 19:30:00+00',
        'scheduled',
        NULL,
        NULL,
        '{}'
    ),
    (
        NULL,
        'friendly',
        'soccer',
        1,
        3,
        '2026-02-15 18:00:00+00',
        'scheduled',
        NULL,
        NULL,
        '{"friendly":true}'
    )
ON CONFLICT DO NOTHING;

INSERT INTO forecasts (
    user_id,
    match_id,
    predicted_home_score,
    predicted_away_score,
    submitted_at
)
VALUES
    (1, 1, 2, 1, '2026-01-12 17:15:00+00'),
    (2, 1, 1, 1, '2026-01-12 17:30:00+00'),
    (1, 2, 1, 1, '2026-01-13 19:15:00+00'),
    (3, 3, 1, 0, '2026-01-20 18:50:00+00')
ON CONFLICT (user_id, match_id) DO NOTHING;

COMMIT;